#! /bin/bash

#########
# example plugin conf
#
# [snmp_hostname_mikrotik_*]
# env.snmpopts -l authNoPriv -u MyUser -a SHA -A MyPassword -r 2

snmphost=$(echo $0 | cut -f2 -d _)

#########
# config
if [ "$1" == "config" ]; then
	echo "host_name $snmphost"
	echo "graph_title temperature"
	echo "graph_category sensors"
	echo "graph_vlabel °C";
	echo "cpu.label CPU"
	exit 0
fi

#########
# data
v=$(snmpget $snmpopts ${snmphost:-127.0.0.1} -Ov -OQ .1.3.6.1.4.1.14988.1.1.3.100.1.3.17 2>/dev/null)
[ $? -gt 0 ] && v=N
echo "cpu.value $v"
