#! /bin/bash

#########
# example plugin conf
#
# [snmp_hostname_mikrotik_*]
# env.snmpopts -l authNoPriv -u MyUser -a SHA -A MyPassword -r 2
# env.iflist		leave empty/unset: dynamically find and name all interfaces
# env.iflist 2 3 5	only show interfaces 2 3 5
# env.iflist eth1 eth2	show ifs 1, 2 and name them eth1, eth2 - these have to be in order and start at if 1. Saves traffic and exectime	
snmphost=$(echo $0 | cut -f2 -d _)

[[ "$iflist" =~ ^[0-9] ]] && ifnum=0
# get interfaces dynamically if list is empty
if [ -z "$iflist" ]; then
	ifnum=$(snmpget $snmpopts ${snmphost:-127.0.0.1} -Ov -OQ .1.3.6.1.2.1.2.1.0)
	if [ $? -eq 0 ]; then
		iflist=$(seq $ifnum)
	else
		exit 2
	fi
fi

#########
# config
if [ "$1" == "config" ]; then
	echo "host_name $snmphost"
	echo "graph_args --base 1000"
	echo "graph_title interface traffic"
	echo "graph_category network"
	echo 'graph_vlabel bits in (-) / out (+) per ${graph_period}'
	echo "graph_info This graph shows the traffic of the eth0 network interface. Please note that the traffic is shown in bits per second, not bytes."

	for i in $iflist; do
		echo $i"in.label in"
		echo $i"in.type DERIVE"
		echo $i"in.graph no"
		echo $i"in.min 0"
		echo $i"in.max 1000000000"
		if [ "$ifnum" ]; then
			echo $i"out.label $(snmpget $snmpopts ${snmphost:-127.0.0.1} -Ov -OQ .1.3.6.1.2.1.2.2.1.2.$i 2>/dev/null)"
		else
			echo $i"out.label $i"
		fi
		echo $i"out.type DERIVE"
		echo $i"out.min 0"
		echo $i"out.max 1000000000"
		echo $i"out.negative $i"in
	done
	exit 0
fi

#########
# data
j=1
for i in $iflist; do
	[ "$ifnum" ] && j=$i
	v=$(snmpget $snmpopts ${snmphost:-127.0.0.1} -Ov -OQ .1.3.6.1.2.1.31.1.1.1.6.$j 2>/dev/null)
	echo $i"in.value $((v*8))"
	v=$(snmpget $snmpopts ${snmphost:-127.0.0.1} -Ov -OQ .1.3.6.1.2.1.31.1.1.1.10.$j 2>/dev/null)
	echo $i"out.value $((v*8))"
	(( j++ ))
done
